# Generated by Django 3.1.1 on 2020-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surpriseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='surprise_views',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewcount',
            name='surprise_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viewcount',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
